### PR TITLE
Fix errors compiling for node v12.0.0

### PR DESCRIPTION
**Pull request by trxcllnt**

### CODE REVIEW

**Comment by robertklep** [comment]
Thanks for your PR :)

However, it's breaking the build on older versions of Node.js:
```
> metrohash@2.5.1 install /home/travis/build/robertklep/node-metrohash
> node-gyp rebuild
make: Entering directory `/home/travis/build/robertklep/node-metrohash/build'
  CXX(target) Release/obj.target/metrohash/src/metrohash_wrapper.o
../src/metrohash_wrapper.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE NodeMetroHash<HashClass, DIGEST_SIZE>::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/metrohash_wrapper.cpp:24:108: error: ‘Nan::imp::ValueFactoryBase<long int>::return_t’ has no member named ‘ToChecked’
             NodeMetroHash* hash = new NodeMetroHash(info[0]->IsUndefined() ? 0 : Nan::To<int64_t>(info[0]).ToChecked());
                                                                                                            ^
../src/metrohash_wrapper.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE NodeMetroHashFn(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/metrohash_wrapper.cpp:133:42: error: ‘Nan::imp::ValueFactoryBase<long int>::return_t’ has no member named ‘ToChecked’
         seed = Nan::To<int64_t>(info[1]).ToChecked();
                                          ^
make: *** [Release/obj.target/metrohash/src/metrohash_wrapper.o] Error 1
make: Leaving directory `/home/travis/build/robertklep/node-metrohash/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v6.17.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v6.17.1/bin/node" "/home/travis/.nvm/versions/node/v6.17.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/robertklep/node-metrohash
gyp ERR! node -v v6.17.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```	

I prefer maintaining backward compatibility, so if you can fix this issue I'd be glad to merge!

**Comment by trxcllnt** [comment]
I did a blanket find/replace for the `value->ToX()` calls after reading the nan [doc on converters](https://github.com/nodejs/nan/blob/3bd8b1b540435256140ea8b5915dbaa1521ecdd7/doc/converters.md). I'm not very familiar with nan nor older versions of v8, so I'm not sure why they're returning an incompatible type here. I'd be happy to make the necessary changes if you have any ideas of where to start.

**Comment by trxcllnt** [comment]
@robertklep looks like `ToChecked` is a newer alias for `FromJust`, so using that instead seems to be working for backwards-compatibility.

**Comment by robertklep** [comment]
Thanks! I had to fix a small issue specific to macOS and Node v6, but other than that, it's working fine on all the versions I test on (v6, v8, v10, v11 and v12 now).

Travis is happy:
image

I'll push a new version shortly.

**Comment by robertklep** [comment]
Released as v2.6.0

**Pull request merged**
